### ISSUE TITLE
Get NoSuchMethodError error while run cucumber test framework

### ISSUE THREAD

**Issue by ansonliao** [saikrishna321/PageObjectPatternAppium#12]
Hi @saikrishna321 ,
I created my cucumber test feature and test steps in java, and run the feature and test steps succeeded, but fail at final in HtmlReporter.generateReports().

the error message please check below.

```java
java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.wrap(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
        at net.masterthought.cucumber.util.ChartUtil.getTags(ChartUtil.java:15)
        at net.masterthought.cucumber.generators.TagsOverviewPage.prepareReport(TagsOverviewPage.java:37)
        at net.masterthought.cucumber.generators.AbstractPage.generatePage(AbstractPage.java:52)
        at net.masterthought.cucumber.ReportBuilder.generateAllPages(ReportBuilder.java:77)
        at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:57)
        at com.appium.cucumber.report.HtmlReporter.generateReports(HtmlReporter.java:48)
        at com.appium.executor.MyTestExecutor.distributeTests(MyTestExecutor.java:80)
        at com.appium.manager.ParallelThread.parallelExecution(ParallelThread.java:140)
        at com.appium.manager.ParallelThread.triggerTest(ParallelThread.java:66)
        at com.appium.manager.ParallelThread.runner(ParallelThread.java:62)
        at com.example.steps.RunnerCukes.testCukesRunner(RunnerCukes.java:15)
```

I can succeed to run this github sample project in cucumber framework, but fail in at my test cases.

and AppiumTestDistribution version same as sample project "PageObjectPatternAppium", version = 5.0.1.

hope can receive your reply soon.

**Comment by saikrishna321** [comment]
@ansonliao can you add this to pom.xml n try 

<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.4</version>
</dependency>

**Comment by ansonliao** [comment]
@saikrishna321 
I fixed the problem by add dependency of commons-lang3, version 3.4, it is strange.

thanks for your reply.

**Comment by saikrishna321** [comment]
i will add this to the dependency pom..
