### ISSUE TITLE
Cannot run program "idevice_id"

### ISSUE THREAD

**Issue by wv1124** [saikrishna321/PageObjectPatternAppium#2]
Running com.appium.tests.Runner
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@12f40c25
creating directory: Logs
🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺
No Device Connected
🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺
java.io.IOException: Cannot run program "idevice_id": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.appium.utils.CommandPrompt.runCommand(CommandPrompt.java:21)
	at com.appium.ios.IOSDeviceConfiguration.getIOSUDID(IOSDeviceConfiguration.java:37)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:61)
	at com.appium.tests.Runner.testRunner(Runner.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 40 more

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

**Comment by saikrishna321** [comment]
This framework triggers your test in parallel across iOS and Android, so fetch if iOS devices are connected we use library idevice 

You need to install brew install ideviceinstaller on your Mac

**Comment by nazim2584** [comment]
Hello Sai,

I am also getting same error on mac machine. I am using following configurations:
OS X: 10.9.5
Xcode: 6.3.1
And i executed this command "brew install libimobiledevice libplist libtasn1 usbmuxd openssl ideviceinstaller" and showing all are already installed. Please suggest me some solutiins.

**Comment by saikrishna321** [comment]
@nazim2584 are your running your tests from command line or eclipse?

**Comment by nazim2584** [comment]
From eclipse using testng...

**Comment by saikrishna321** [comment]
@nazim2584 you need to set PATH in eclipse under environment. This will work fine in intellji 

https://cloud.githubusercontent.com/assets/4045041/12191064/04580240-b5f6-11e5-8608-bd6145a862ef.png

**Comment by nazim2584** [comment]
@saikrishna321  Thanks Sai.. I tried to set the path for eclipse but still it is not working..

**Comment by saikrishna321** [comment]
Can u pls share screenshot ?

**Comment by nazim2584** [comment]
Find the scrrenshot for path...
![image](https://cloud.githubusercontent.com/assets/21053701/17695897/72df6bec-63c8-11e6-80fe-9858869f9872.png)
For Error:
![image](https://cloud.githubusercontent.com/assets/21053701/17695922/8d6fa210-63c8-11e6-82c5-56a8cf5846dc.png)

**Comment by saikrishna321** [comment]
@nazim2584 you have set just the ANDROID_HOME u need to set PATH
https://cloud.githubusercontent.com/assets/4927589/10269824/c6ddb42a-6ae9-11e5-822f-3d361b5a5e34.png

**Comment by nazim2584** [comment]
Thank u so much...
Hurray!!... Now it's working....

**Comment by nazim2584** [comment]
Hello Sai,
I am getting this exception while executing this framework in IOS io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: 
![screen shot 2016-08-29 at 5 46 51 pm](https://cloud.githubusercontent.com/assets/21053701/18051202/b684cdf4-6e10-11e6-894a-75dd70f827a6.png)

**Comment by saikrishna321** [comment]
@nazim2584 pls check if the appium server path is correct

**Comment by nazim2584** [comment]
I have checked the path and it is correct:-
/Applications/Appium.app/Contents/Resources/node_modules/appium/build/lib/main.js

**Comment by saikrishna321** [comment]
can u install appium through node n replace the location

**Comment by nazim2584** [comment]
Thanks @saikrishna321 I will try to install appium through node but  have a one question.
Should i need to uninstall the existing appium.app?
Sample code:
AppiumServiceBuilder builder = new AppiumServiceBuilder()
		.usingDriverExecutable(new File("/usr/local/bin/node"))
        .withAppiumJS(new File("/Applications/Appium.app/Contents/Resources/node_modules/appium/build/lib/main.js"))
        .withArgument(GeneralServerFlag.LOG_LEVEL, "info")
        .withLogFile(new File(System.getProperty("user.dir") + "/target/appiumlogs/sample.txt"))
        .usingAnyFreePort();
			appiumDriverLocalService = builder.build();
			appiumDriverLocalService.start();

**Comment by nazim2584** [comment]
@saikrishna321, I resolved it. Just need to add the parameter as ipAddress i.e 127.0.01:4723
It is not working with default ip 0.0.0.04723.
AppiumServiceBuilder builder = new AppiumServiceBuilder()
		.usingDriverExecutable(new File("/usr/local/bin/node"))
       .withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js"))
        .withArgument(GeneralServerFlag.LOG_LEVEL, "info")
        .withIPAddress("127.0.0.1")
     
        .usingAnyFreePort();
			appiumDriverLocalService = builder.build();
	     	appiumDriverLocalService.start();
Thanks for your quick reply @saikrishna321
