### ISSUE TITLE
cucumber test cases are not executing

### ISSUE THREAD

**Issue by dkjha52** [saikrishna321/PageObjectPatternAppium#25]
Set the below value in properties file - 
FRAMEWORK=cucumber
Note  - use the same pom.xml conrents mention in the project

Getting below output - 
------------------------
***************************************************

Total Number of devices detected::1

***************************************************

starting running tests in threads
Adding iOS devices
Adding Android devices
{emulator-5554=true}
...
... TestNG 6.9.10 by Cédric Beust (cedric@beust.com)
...

[TestNG] Running:
  Command line suite

[ThreadUtil] Starting executor timeOut:2147483647ms workers:1 threadPoolSize:1

===============================================
    TestNG Test0
    Tests run: 0, Failures: 0, Skips: 0
===============================================

===============================================
TestNG Forum
Total tests run: 0, Failures: 0, Skips: 0
===============================================

**Comment by saikrishna321** [comment]
@dkjha52 can you share the config.properties

**Comment by dkjha52** [comment]
@saikrishna321 Here is conf properties file - 
ANDROID_APP_PATH=/Users/admin/Documents/Automation/AppiumDistribution/build/wordpress.apk
APP_PACKAGE=org.wordpress.android
APP_ACTIVITY=org.wordpress.android.ui.WPLaunchActivity
RUNNER=parallel
APPIUM_JS_PATH=/Applications/Appium.app/Contents/Resources/node_modules/appium/build/lib/main.js
BROWSER_TYPE=chrome
APP_TYPE=NA
FRAMEWORK=cucumber
MONGODB_SERVER=127.0.0.1
MONGODB_PORT=27017

**Comment by saikrishna321** [comment]
@dkjha52 can u confirm if there is output directory created under test root

**Comment by dkjha52** [comment]
@saikrishna321 No, Output is not creating under the test root. I can see parallelCucumber.xml created under target directory.

**Comment by saikrishna321** [comment]
@dkjha52 can you run the command mvn clean validate and check output folder is created

**Comment by dkjha52** [comment]
@saikrishna321 I ran the command "mvn clean validate" and executed successfully but output folder is not created

**Comment by dkjha52** [comment]
adminisatorsmbp:AppiumDistribution admin$ mvn clean validate
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building AppiumDistribution 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ AppiumDistribution ---
[INFO] Deleting /Users/adminDocuments/DevBuildAutomation/AppiumDistribution/target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.405 s
[INFO] Finished at: 2016-12-13T12:08:04+05:30
[INFO] Final Memory: 6M/123M
[INFO] ------------------------------------------------------------------------

**Comment by saikrishna321** [comment]
i just checked and it generates the output folder with all runner files. Can you share your project

**Comment by dkjha52** [comment]
[AppiumDistribution.zip](https://github.com/saikrishna321/PageObjectPatternAppium/files/648284/AppiumDistribution.zip)
I am using the same example as you have mentioned. Please find the attachment.

**Comment by saikrishna321** [comment]
@dkjha52 please remove the <pluginManagement> </pluginManagement>  tag and make sure 
<useTestNG>true</useTestNG> you also need to add AppiumParallelDistribution dependency. Refer the current project pom.xml 

mvn clean validate will generate output folder with runner files

**Comment by dkjha52** [comment]
I tried the same (added the AppiumParallelDistribution dependency) but getting the same. Can you please let me know which maven version are you using. I am using maven 3.3.9 version with JDK8.

Here is error I am getting - 
----------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project PagePatternAppium: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/admin/Documents/PageObjectPatternAppium-master/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project PagePatternAppium: There are test failures.

**Comment by saikrishna321** [comment]
@dkjha52  i have the same version of mvn and jdk 1.8, can u just clone this project and give it a try ?

**Comment by dkjha52** [comment]
@saikrishna321 I have cloned the project tried the same. Getting below error message with below configuration - 

RUNNER=parallel
FRAMEWORK=cucumber
--------------------------------------------
Total Number of devices detected::2

***************************************************

starting running tests in threads
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.091 sec <<< FAILURE! - in com.appium.steps.RunnerCukes
testCukesRunner on testCukesRunner(com.appium.steps.RunnerCukes)(com.appium.steps.RunnerCukes)  Time elapsed: 1.646 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at com.appium.executor.MyTestExecutor.deleteOutputDirectory(MyTestExecutor.java:339)
	at com.appium.executor.MyTestExecutor.parallelTests(MyTestExecutor.java:130)
	at com.appium.manager.ParallelThread.parallelExecution(ParallelThread.java:147)
	at com.appium.manager.ParallelThread.triggerTest(ParallelThread.java:66)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:62)
	at com.appium.steps.RunnerCukes.testCukesRunner(RunnerCukes.java:12)


Results :

Failed tests: 
  RunnerCukes.testCukesRunner:12 » NullPointer

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
