### ISSUE TITLE
When run a single testcase an exception error(java.lang.ExceptionInInitializerError) show up

### ISSUE THREAD

**Issue by SuperExpectation** [saikrishna321/PageObjectPatternAppium#26]
ENV:
System: win8 64x
appium: 1.4.16
node: 6.9.4

Reproduction:
Try to run testcase loginWithInValidUser under Utils.java. The following error show up, if annotate 'logStepIntoExtentReport' under enterUserAndPassword function, it works as expectation.

java.io.IOException: Cannot run program "appium": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.appium.utils.CommandPrompt.runCommand(CommandPrompt.java:21)
	at com.report.factory.ExtentManager.getExtent(ExtentManager.java:50)
	at com.report.factory.ExtentTestManager.<clinit>(ExtentTestManager.java:14)
	at com.appium.config.CommonAppiumTest.logStepIntoExtentReport(CommonAppiumTest.java:122)
	at com.appium.pages.LoginPage.enterUserAndPassword(LoginPage.java:42)
	at com.appium.screen.flows.AndroidFlow.login(AndroidFlow.java:18)
	at com.appium.pages.LoginPage.enterValidCredentails(LoginPage.java:27)
	at com.appium.config.Utils.loginWithInValidUser(Utils.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 35 more
FAILED: loginWithInValidUser
java.lang.ExceptionInInitializerError
	at com.appium.config.CommonAppiumTest.logStepIntoExtentReport(CommonAppiumTest.java:122)
	at com.appium.pages.LoginPage.enterUserAndPassword(LoginPage.java:42)
	at com.appium.screen.flows.AndroidFlow.login(AndroidFlow.java:18)

**Comment by saikrishna321** [comment]
@SuperExpectation make sure you have appium install from npm install -g appium
