### ISSUE TITLE
Error while running tests.

### ISSUE THREAD

**Issue by VenkateshPS** [saikrishna321/PageObjectPatternAppium#38]
Hi Sai,

I cloned your project and tried running tests, I get below error, moreover I don't see Appium driver getting created. 

Where are you creating driver.

    public static AppiumDriver getDriver() {
        return (AppiumDriver)appiumDriver.get();
    }

does not seems to returning driver.

Running TestSuite
Configuring TestNG with: TestNG652Configurator
Tests run: 8, Failures: 8, Errors: 0, Skipped: 0, Time elapsed: 0.485 sec <<< FAILURE! - in TestSuite
addComment(com.appium.tests.AddCommentTest)  Time elapsed: 0.159 sec  <<< FAILURE!
java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field com.appium.page.objects.LoginPageObjects.username to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$dd998978
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
	at com.appium.pages.LoginPage.<init>(LoginPage.java:24)
	at com.appium.tests.AddCommentTest.addComment(AddCommentTest.java:20)

**Comment by saikrishna321** [comment]
can u pls mention how r u running it ?

**Comment by VenkateshPS** [comment]
I did **mvn clean compile install**from command line, also ran from Intelij IDE by right click run LoginTest.java

**Comment by saikrishna321** [comment]
@VenkateshPS pls run Platform="android" mvn clean -Dtest=Runner test

**Comment by VenkateshPS** [comment]
@saikrishna321  it works, if you don't mind can you talk a little about the flow.
How is driver getting created?
Appium server starts in same command line.
How do you run tests from IDE or testng.xml

are you there on Skype?

**Comment by saikrishna321** [comment]
@VenkateshPS you can join the slack channel 

https://join.slack.com/appiumtestparallel/shared_invite/MjA5NTQ4NDkwNTgzLTE0OTkzNDM5NzYtYTY1M2UwNDZhNA
