### ISSUE TITLE
Getting below issue. Please help.

### ISSUE THREAD

**Issue by prbale** [saikrishna321/PageObjectPatternAppium#42]
Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
java.lang.NullPointerException
        at com.appium.manager.DeviceAllocationManager.initializeDevices(DeviceAllocationManager.java:40)
        at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:27)
        at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:32)
        at com.appium.manager.ParallelThread.<init>(ParallelThread.java:47)
        at com.appium.tests.Runner.testRunner(Runner.java:12)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:776)
        at org.testng.TestRunner.run(TestRunner.java:634)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
        at org.testng.SuiteRunner.run(SuiteRunner.java:334)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
        at org.testng.TestNG.runSuites(TestNG.java:1161)
        at org.testng.TestNG.run(TestNG.java:1129)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:126)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:117)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
Failed to initialize framework

**Comment by saikrishna321** [comment]
Platform="andriod" mvn clean -Dtest=Runner test

this should fix

**Comment by saikrishna321** [comment]
@prbale has this fixed ?
