### ISSUE TITLE
ClassNotFoundException for cucumber reporting..

### ISSUE THREAD

**Issue by rahul-bhiwagade** [saikrishna321/PageObjectPatternAppium#45]
I have done all the setting to run cucumber test cases via 
Platform=android mvn clean -Dtest=RunnerCukes test

I keep getting below error message please help me understand how to resolve this..

 T E S T S
-------------------------------------------------------
Running com.appium.steps.RunnerCukes
Configuring TestNG with: TestNG652Configurator
Adding all android devices: 192.168.62.101:5555
Adding all android devices: 192.168.62.102:5555
Adding all android devices: 192.168.62.103:5555
Adding Android devices
{192.168.62.102:5555=true, 192.168.62.103:5555=true, 192.168.62.101:5555=true}
                            _  _        _ 
 _ __    __ _  _ __   __ _ | || |  ___ | |
| '_ \  / _` || '__| / _` || || | / _ \| |
| |_) || (_| || |   | (_| || || ||  __/| |
| .__/  \__,_||_|    \__,_||_||_| \___||_|
|_|                                       

creating directory: Logs
creating directory: ADBLogs
Android 192.168.62.101:5555 Directory is created!
Android 192.168.62.102:5555 Directory is created!
Android 192.168.62.103:5555 Directory is created!
***************************************************

Total Number of devices detected::3

***************************************************

starting running tests in threads
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.049 sec <<< FAILURE! - in com.appium.steps.RunnerCukes
testCukesRunner on testCukesRunner(com.appium.steps.RunnerCukes)(com.appium.steps.RunnerCukes)  Time elapsed: 1.193 sec  <<< FAILURE!
java.lang.RuntimeException: java.lang.ClassNotFoundException: /cucumber-reporting-2/1/0/jar(HelloCucumber
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.appium.manager.PackageUtil.lambda$getClasses$0(PackageUtil.java:33)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.appium.manager.PackageUtil.getClasses(PackageUtil.java:38)
	at com.appium.manager.ParallelThread.parallelExecution(ParallelThread.java:139)
	at com.appium.manager.ParallelThread.triggerTest(ParallelThread.java:80)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:72)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:76)
	at com.appium.steps.RunnerCukes.testCukesRunner(RunnerCukes.java:12)

**Comment by qafarabi** [comment]
@saikrishna321

**Comment by saikrishna321** [comment]
let me reproduce it from my side ...

**Comment by saikrishna321** [comment]
@rahul-bhiwagade @qafarabi Can reproduce the issue ??? Can you pls raise on the AppiumTestDistribution repo.
