### ISSUE TITLE
Error testRunner(com.appium.tests.Runner)  not able to run sample project

### ISSUE THREAD

**Issue by vikramvi** [saikrishna321/PageObjectPatternAppium#5]
After running command mvn clean -Dtest=Runner test , getting below error.

I did few changes to remove compilation errors in forked repo's branch https://github.com/vikramvi/PageObjectPatternAppium/tree/vikramvi/bug_fixes

I have an android emulator and android physical devices connected to Mac.

Please check , I tried to look into code but not yet understood it completely.

` Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
creating directory: Logs
creating directory: ADBLogs
Android emulator-5554 Directory is created!
Android 000007CF003ACABB Directory is created!
Total Number of devices detected::2
starting running tests in threads
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.1 sec <<< FAILURE! - in com.appium.tests.Runner
testRunner(com.appium.tests.Runner)  Time elapsed: 0.702 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at com.appium.executor.MyTestExecutor.deleteOutputDirectory(MyTestExecutor.java:246)
	at com.appium.executor.MyTestExecutor.parallelTests(MyTestExecutor.java:101)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:102)
	at com.appium.tests.Runner.testRunner(Runner.java:12)

Results :

Failed tests: 
  Runner.testRunner:12 » NullPointer

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0 `

Thanks & Regards,
Vikram

**Comment by vikramvi** [comment]
`vikrams-mbp:PageObjectPatternAppium vikram-anna$ mvn clean -e -Dtest=Runner test
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building PagePatternAppium 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.relevantcodes:extentreports:jar:2.41.0-SNAPSHOT is missing, no dependency information available
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ PagePatternAppium ---
[INFO] Deleting /Users/vikram-anna/Documents/workspace/PageObjectPatternAppium/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ PagePatternAppium ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/vikram-anna/Documents/workspace/PageObjectPatternAppium/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ PagePatternAppium ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ PagePatternAppium ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 16 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ PagePatternAppium ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 32 source files to /Users/vikram-anna/Documents/workspace/PageObjectPatternAppium/target/test-classes
[WARNING] /Users/vikram-anna/Documents/workspace/PageObjectPatternAppium/src/test/java/com/appium/config/Utils.java: /Users/vikram-anna/Documents/workspace/PageObjectPatternAppium/src/test/java/com/appium/config/Utils.java uses or overrides a deprecated API.
[WARNING] /Users/vikram-anna/Documents/workspace/PageObjectPatternAppium/src/test/java/com/appium/config/Utils.java: Recompile with -Xlint:deprecation for details.
[WARNING] /Users/vikram-anna/Documents/workspace/PageObjectPatternAppium/src/test/java/com/appium/steps/MyStepdefs.java: /Users/vikram-anna/Documents/workspace/PageObjectPatternAppium/src/test/java/com/appium/steps/MyStepdefs.java uses unchecked or unsafe operations.
[WARNING] /Users/vikram-anna/Documents/workspace/PageObjectPatternAppium/src/test/java/com/appium/steps/MyStepdefs.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ PagePatternAppium ---
[INFO] Surefire report directory: /Users/vikram-anna/Documents/workspace/PageObjectPatternAppium/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
creating directory: Logs
creating directory: ADBLogs
Android emulator-5554 Directory is created!
Android 000007CF003ACABB Directory is created!
Total Number of devices detected::2
starting running tests in threads
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.117 sec <<< FAILURE! - in com.appium.tests.Runner
testRunner(com.appium.tests.Runner)  Time elapsed: 0.699 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at com.appium.executor.MyTestExecutor.deleteOutputDirectory(MyTestExecutor.java:246)
	at com.appium.executor.MyTestExecutor.parallelTests(MyTestExecutor.java:101)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:102)
	at com.appium.tests.Runner.testRunner(Runner.java:12)


Results :

Failed tests: 
  Runner.testRunner:12 » NullPointer

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.799 s
[INFO] Finished at: 2016-06-08T17:24:50+02:00
[INFO] Final Memory: 23M/246M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project PagePatternAppium: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/vikram-anna/Documents/workspace/PageObjectPatternAppium/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project PagePatternAppium: There are test failures.

Please refer to /Users/vikram-anna/Documents/workspace/PageObjectPatternAppium/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /Users/vikram-anna/Documents/workspace/PageObjectPatternAppium/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:82)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:254)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:854)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:722)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
vikrams-mbp:PageObjectPatternAppium vikram-anna$`

**Comment by saikrishna321** [comment]
@vikramvi  as part of 4.0.2 i added the com.relevantcodes:extentreports:jar:2.41.0-SNAPSHOT in the tagged v4.0.2. my bad 

as you have added in your pom.xml thats the fix for now.. In the master i have updated it...

**Comment by vikramvi** [comment]
@saikrishna321  Just to clarify the failure is in my branch itself even after adding entry for extentreports in pom.xml.  

Did you mean I need to remove this and update version of framework with fix ?

**Comment by saikrishna321** [comment]
@vikramvi can you try with the below dependency, if you still have issues please add me on gitter/skype(sai.krishna560) 

```
<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>f6f1e7df96</version>
	</dependency>
```

**Comment by rajamobiletech** [comment]
@saikrishna321 Even i am facing the same issue.

`-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
creating directory: Logs
creating directory: ADBLogs
Android 192.168.56.101:5555 Directory is created!
Total Number of devices detected::1
starting running tests in threads
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.612 sec <<< FAILURE! - in com.appium.tests.Runner
testRunner(com.appium.tests.Runner)  Time elapsed: 0.291 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at com.appium.executor.MyTestExecutor.deleteOutputDirectory(MyTestExecutor.java:246)
	at com.appium.executor.MyTestExecutor.distributeTests(MyTestExecutor.java:62)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:99)
	at com.appium.tests.Runner.testRunner(Runner.java:12)


Results :

Failed tests:
  Runner.testRunner:12 » NullPointer

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.827 s
[INFO] Finished at: 2016-06-17T19:08:03+05:30
[INFO] Final Memory: 24M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project PagePatternAppium: There are test failures.`

**Comment by saikrishna321** [comment]
@rajamobiletech can you please change the FRAMEWORK=testng in config file
